print("hello")
print("hello python")
print('hello bengalore')
print("python","java","web")
print("hello python",end=" ")
print("programming")
print("java","python","web",sep="/")
print("java","python","web",sep="$")
print("ramya","sravanthi","kavya",sep="@")
print("Hello","Hi",end=" ",sep="/")
print("welcome to Bengalore")